config/routes.rb
Rails.application.routes.draw do

  get 'quiz/quiz'

  namespace :api do
    namespace :v1 do
      resources :quizzes
      resources :categories
      resources :information_types
      resources :answers
      resources :informations
      resources :quiz_informations
      resources :memes

      resources :answer_givens

      devise_scope :user do
        get '/password/edit' => 'fm_passwords#edit', as: 'edit_password'
        post '/password' => 'fm_passwords#create'
        put '/password' => 'fm_passwords#update'
        put '/users' => 'fm_registrations#update'
      end

      get '/jwt_token' => 'fm_jwt_token#show'
      post '/jwt_token' => 'fm_jwt_token#create'
      delete '/jwt_token' => 'fm_jwt_token#destroy'
      get 'api_authenticated_nothing' => 'fm_base#authenticated_nothing'
    end
  end

  namespace :admin do
    resources :quizzes
    resources :categories
    resources :information_types
    resources :answers
    resources :informations
    resources :quiz_informations
    resources :memes
    resources :users

    get 'admin_authenticated_nothing' => 'fm_base#admin_authenticated_nothing'
    get '/' => 'fm_base#admin_authenticated_nothing', as: 'root'
  end

  get 'quiz' => 'quiz#quiz'

  authenticate :user, lambda {|u| u.admin? || u.super_admin? } do
    apipie
  end

  devise_for :users

  unless Rails.env.test?
    get '*unmatched_route', :to => 'application#raise_not_found!'
  end

  root 'application#nothing'

end

app/models/information.rb
class Information < ApplicationRecord
  belongs_to :information_type
  belongs_to :correct_answer, class_name: 'Answer'
  belongs_to :category

  def answers
    self.information_type.answers
  end

  scope :for_user, -> (user) do
    all
  end
end

app/models/information_type.rb
class InformationType < ApplicationRecord
  has_many :answers
  has_many :informations

  scope :for_user, -> (user) do
    all
  end

end

app/controllers/admin/informations_controller.rb
module Admin
  class InformationsController < FmBaseController
    layout 'admin/admin'

    before_action :authenticate_admin!

    before_action :set_information, only: [:show, :edit, :update, :destroy]

    # GET /informations
    # GET /informations.json
    def index
      @informations = Information.all
      @informations = filter_simple_search(@informations, :id)
    end

    # GET /informations/1
    # GET /informations/1.json
    def show
    end

    # GET /informations/new
    def new
      @information = Information.new
    end

    # GET /informations/1/edit
    def edit
    end

    # POST /informations
    # POST /informations.json
    def create
      @information = Information.new(information_params)

      respond_to do |format|
        if @information.save
          format.html { redirect_to edit_admin_information_path(@information), notice: 'Information was successfully created.' }
          format.json { render :show, status: :created, location: @information }
        else
          format.html { render :new }
          format.json { render json: @information.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /informations/1
    # PATCH/PUT /informations/1.json
    def update
      respond_to do |format|
        if @information.update(information_params)
          format.html { redirect_to edit_admin_information_path(@information), notice: 'Information was successfully updated.' }
          format.json { render :show, status: :ok, location: @information }
        else
          format.html { render :edit }
          format.json { render json: @information.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /informations/1
    # DELETE /informations/1.json
    def destroy
      @information.destroy
      respond_to do |format|
        format.html { redirect_to admin_informations_url }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_information
        @information = Information.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def information_params
        params.require(:information).permit(:challenge_text, :result_text, :information_type_id, :source_link, :correct_answer_id, :category_id)
      end
  end
end

app/controllers/api/v1/informations_controller.rb
module Api
  module V1
    class InformationsController < FmBaseController

      before_action :authenticate!
      before_action :set_information, only: [:show, :update, :destroy]

      # GET /informations.json
      # DOC GENERATED AUTOMATICALLY: REMOVE THIS LINE TO PREVENT REGENARATING NEXT TIME
      api :GET, '/v1/informations', 'List informations'
      def index
        @informations = Information.for_user(current_user)
      end

      # GET /informations/1.json
      # DOC GENERATED AUTOMATICALLY: REMOVE THIS LINE TO PREVENT REGENARATING NEXT TIME
      api :GET, '/v1/informations/:id', 'Show an information'
      def show
      end

      # POST /informations.json
      def create
        @information = Information.new(information_params)

        if @information.save_with_user(current_user)
          render :show, status: :created, location: [:api, :v1, @information]
        else
          render json: @information.errors, status: :unprocessable_entity
        end
      end

      # PATCH/PUT /informations/1.json
      def update
        if @information.update_with_user(current_user, information_params)
          render :show, status: :ok, location: [:api, :v1, @information]
        else
          render json: @information.errors, status: :unprocessable_entity
        end
      end

      # DELETE /informations/1.json
      # DOC GENERATED AUTOMATICALLY: REMOVE THIS LINE TO PREVENT REGENARATING NEXT TIME
      api :DELETE, '/v1/informations/:id', 'Destroy an information'
      def destroy
        @information.destroy_with_user(current_user)
        head :no_content
      end

      private
        # Use callbacks to share common setup or constraints between actions.
        def set_information
          @information = Information.for_user(current_user).find(params[:id])
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def information_params
          params.require(:information).permit(:challenge_text, :result_text, :information_type_id, :source_link, :correct_answer_id, :category_id)
        end
    end
  end
end

app/helpers/informations_helper.rb
module InformationsHelper
end

app/views/admin/informations/_form.html.erb
<%= form_for [:admin, @information], :html => {:class => "form-horizontal", :role => 'form'} do |f| %>
  <% if @information.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@information.errors.count, "error") %> prohibited this information from being saved:</h2>

      <ul>
      <% @information.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="space-4"></div>

  <%= render partial: 'form_fields', locals: { f: f } %>

  <div class="clearfix form-actions">
    <div class="col-md-offset-3 col-md-9">
      <button class="btn btn-info" type="submit"><i class="icon-ok bigger-110"></i> Submit</button>
    </div>
  </div>
<% end %>

app/views/admin/informations/_form_fields.html.erb
<div class="form-group">
  <%= f.label :id, "#{t('Id')}:", class: "control-label col-xs-12 col-sm-3 no-padding-right" %>
  <div class="col-xs-12 col-sm-9">
    <div class="clearfix">
      <%= f.text_field :id, disabled: true , class: "col-xs-12 col-sm-6"%>
    </div>
  </div>
</div>
<div class="space-2"></div>


<div class="form-group">
  <%= f.label :challenge_text, "#{t('Challenge_text')}:", class: "control-label col-xs-12 col-sm-3 no-padding-right" %>
  <div class="col-xs-12 col-sm-9">
    <div class="clearfix">
      <%= f.text_area :challenge_text, class: "col-xs-12 col-sm-6", rows: 9 %>
    </div>
  </div>
</div>
<div class="space-2"></div>


<div class="form-group">
  <%= f.label :result_text, "#{t('Result_text')}:", class: "control-label col-xs-12 col-sm-3 no-padding-right" %>
  <div class="col-xs-12 col-sm-9">
    <div class="clearfix">
      <%= f.text_area :result_text, class: "col-xs-12 col-sm-6", rows: 9 %>
    </div>
  </div>
</div>
<div class="space-2"></div>

<div class="form-group">
  <%= f.label :information_type_id, "#{t('Information_type')}:", class: "control-label col-xs-12 col-sm-3 no-padding-right" %>
  <div class="col-xs-12 col-sm-9">
    <div class="clearfix">
      <%= f.select :information_type_id, InformationType.all.map { |information_type| [information_type.title, information_type.id] }, include_blank: true, class: "col-xs-12 col-sm-6"%>
    </div>
  </div>
</div>
<div class="space-2"></div>

<div class="form-group">
  <%= f.label :source_link, "#{t('Source_link')}:", class: "control-label col-xs-12 col-sm-3 no-padding-right" %>
  <div class="col-xs-12 col-sm-9">
    <div class="clearfix">
      <%= f.text_field :source_link, class: "col-xs-12 col-sm-6"%>
    </div>
  </div>
</div>
<div class="space-2"></div>

<div class="form-group">
  <%= f.label :correct_answer_id, "#{t('Correct_answer')}:", class: "control-label col-xs-12 col-sm-3 no-padding-right" %>
  <div class="col-xs-12 col-sm-9">
    <div class="clearfix">
      <%= f.select :correct_answer_id, Answer.all.map { |answer| [answer.text, answer.id] }, include_blank: true, class: "col-xs-12 col-sm-6"%>
    </div>
  </div>
</div>
<div class="space-2"></div>


<div class="form-group">
  <%= f.label :category_id, "#{t('Category')}:", class: "control-label col-xs-12 col-sm-3 no-padding-right" %>
  <div class="col-xs-12 col-sm-9">
    <div class="clearfix">
      <%= f.select :category_id, Category.all.map { |category| [category.title, category.id] }, include_blank: true, class: "col-xs-12 col-sm-6"%>
    </div>
  </div>
</div>
<div class="space-2"></div>

app/views/admin/informations/edit.html.erb
<h1>Editing information</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @information] %> |
<%= link_to 'Back', admin_informations_path %>

app/views/admin/informations/index.html.erb
<div class="row">
  <div class="col-md-6">
    <%= render :partial => 'shared/simple_search', :locals => { path: admin_informations_path} %>
  </div>


  <div class="col-md-offset-4 col-md-2 top-action">
    <%= link_to content_tag(:span, '', :class => %w(glyphicon glyphicon-plus)).html_safe + content_tag(:span, " #{t('New')} #{t('Information')}", :class => "action-label").html_safe, new_admin_information_path, :class => %w(btn btn-primary btn-block) %>
  </div>

  <div class="col-xs-12">
    <div class="table-responsive">
      <table id="sample-table-1" class="table table-striped table-bordered table-hover">
        <thead>
          <tr>
            <th>Id</th>
            <th>Challenge text</th>
            <th>Result text</th>
            <th>Information type</th>
            <th>Source link</th>
            <th>Correct answer</th>
            <th>Category</th>
            <th>Created at</th>
            <th>Updated at</th>
            <th>Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @informations.each do |information| %>
            <tr>
                    <td><%= information.id %></td>
                    <td><%= information.challenge_text %></td>
                    <td><%= information.result_text %></td>
                    <td><%= "#{information.information_type.title} (#{information.information_type_id})" %></td>
                    <td><%= information.source_link %></td>
                    <td><%= "#{information.correct_answer.text} (#{information.correct_answer_id})" %></td>
                    <td><%= "#{information.category.title} (#{information.category_id})" %></td>
                    <td><%= information.created_at %></td>
                    <td><%= information.updated_at %></td>
                    <td>
                <div class='visible-md visible-lg hidden-sm hidden-xs btn-group'>

                  <%= link_to edit_admin_information_path(information) do %>
                    <button class='btn btn-xs btn-info'><i class='icon-edit bigger-120'></i></button>
                  <% end %>
                  <%= link_to admin_information_path(information), method: :delete, data: { confirm: 'Are you sure?' } do %>
                    <button class='btn btn-xs btn-danger'><i class='icon-trash bigger-120'></i></button>
                  <% end %>
                </div>

                <div class='visible-xs visible-sm hidden-md hidden-lg'>
                  <div class="inline position-relative">
                    <button class="btn btn-minier btn-primary dropdown-toggle" data-toggle="dropdown"><i class="icon-cog icon-only bigger-110"></i></button>
                    <ul class="dropdown-menu dropdown-only-icon dropdown-yellow pull-right dropdown-caret dropdown-close">

                      <li>
                        <%= link_to edit_admin_information_path(information), :class => "tooltip-success" do %>
                          <span class="green"><i class="icon-edit bigger-120"></i></span>
                        <% end %>
                      </li>
                      <li>
                        <%= link_to admin_information_path(information), method: :delete, data: { confirm: 'Are you sure?' }, :class => "tooltip-error" do %>
                          <span class="red"><i class="icon-trash bigger-120"></i></span>
                        <% end %>
                      </li>
                    </ul>
                  </div>
                </div>
                
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div><!--/.table-responsive-->
  </div><!--/span-->
</div><!--/row-->

app/views/admin/informations/new.html.erb
<h1>New information</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_informations_path %>