config/routes.rb
Rails.application.routes.draw do

  get 'quiz/quiz'

  namespace :api do
    namespace :v1 do
      resources :quizzes
      resources :categories
      resources :information_types
      resources :answers
      resources :informations
      resources :quiz_informations
      resources :memes

      resources :answer_givens

      devise_scope :user do
        get '/password/edit' => 'fm_passwords#edit', as: 'edit_password'
        post '/password' => 'fm_passwords#create'
        put '/password' => 'fm_passwords#update'
        put '/users' => 'fm_registrations#update'
      end

      get '/jwt_token' => 'fm_jwt_token#show'
      post '/jwt_token' => 'fm_jwt_token#create'
      delete '/jwt_token' => 'fm_jwt_token#destroy'
      get 'api_authenticated_nothing' => 'fm_base#authenticated_nothing'
    end
  end

  namespace :admin do
    resources :quizzes
    resources :categories
    resources :information_types
    resources :answers
    resources :informations
    resources :quiz_informations
    resources :memes
    resources :users

    get 'admin_authenticated_nothing' => 'fm_base#admin_authenticated_nothing'
    get '/' => 'fm_base#admin_authenticated_nothing', as: 'root'
  end

  get 'quiz' => 'quiz#quiz'

  authenticate :user, lambda {|u| u.admin? || u.super_admin? } do
    apipie
  end

  devise_for :users

  unless Rails.env.test?
    get '*unmatched_route', :to => 'application#raise_not_found!'
  end

  root 'application#nothing'

end

app/controllers/admin/quizzes_controller.rb
module Admin
  class QuizzesController < FmBaseController
    layout 'admin/admin'

    before_action :authenticate_admin!

    before_action :set_quiz, only: [:show, :edit, :update, :destroy]

    # GET /quizzes
    # GET /quizzes.json
    def index
      @quizzes = Quiz.all
      @quizzes = filter_simple_search(@quizzes, :id)
    end

    # GET /quizzes/1
    # GET /quizzes/1.json
    def show
    end

    # GET /quizzes/new
    def new
      @quiz = Quiz.new
    end

    # GET /quizzes/1/edit
    def edit
    end

    # POST /quizzes
    # POST /quizzes.json
    def create
      @quiz = Quiz.new(quiz_params)

      respond_to do |format|
        if @quiz.save
          format.html { redirect_to edit_admin_quiz_path(@quiz), notice: 'Quiz was successfully created.' }
          format.json { render :show, status: :created, location: @quiz }
        else
          format.html { render :new }
          format.json { render json: @quiz.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /quizzes/1
    # PATCH/PUT /quizzes/1.json
    def update
      respond_to do |format|
        if @quiz.update(quiz_params)
          format.html { redirect_to edit_admin_quiz_path(@quiz), notice: 'Quiz was successfully updated.' }
          format.json { render :show, status: :ok, location: @quiz }
        else
          format.html { render :edit }
          format.json { render json: @quiz.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /quizzes/1
    # DELETE /quizzes/1.json
    def destroy
      @quiz.destroy
      respond_to do |format|
        format.html { redirect_to admin_quizzes_url }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_quiz
        @quiz = Quiz.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def quiz_params
        params.require(:quiz).permit(:title, quiz_informations_attributes: [:id, :information_id, :_destroy])
      end
  end
end

app/controllers/api/v1/quizzes_controller.rb
module Api
  module V1
    class QuizzesController < FmBaseController

      before_action :authenticate!
      before_action :set_quiz, only: [:show, :update, :destroy]

      # GET /quizzes.json
      # DOC GENERATED AUTOMATICALLY: REMOVE THIS LINE TO PREVENT REGENARATING NEXT TIME
      api :GET, '/v1/quizzes', 'List quizzes'
      def index
        @quizzes = Quiz.for_user(current_user)
      end

      # GET /quizzes/1.json
      # DOC GENERATED AUTOMATICALLY: REMOVE THIS LINE TO PREVENT REGENARATING NEXT TIME
      api :GET, '/v1/quizzes/:id', 'Show a quiz'
      def show
      end

      # POST /quizzes.json
      def create
        @quiz = Quiz.new(quiz_params)

        if @quiz.save_with_user(current_user)
          render :show, status: :created, location: [:api, :v1, @quiz]
        else
          render json: @quiz.errors, status: :unprocessable_entity
        end
      end

      # PATCH/PUT /quizzes/1.json
      def update
        if @quiz.update_with_user(current_user, quiz_params)
          render :show, status: :ok, location: [:api, :v1, @quiz]
        else
          render json: @quiz.errors, status: :unprocessable_entity
        end
      end

      # DELETE /quizzes/1.json
      # DOC GENERATED AUTOMATICALLY: REMOVE THIS LINE TO PREVENT REGENARATING NEXT TIME
      api :DELETE, '/v1/quizzes/:id', 'Destroy a quiz'
      def destroy
        @quiz.destroy_with_user(current_user)
        head :no_content
      end

      private
        # Use callbacks to share common setup or constraints between actions.
        def set_quiz
          @quiz = Quiz.for_user(current_user).find(params[:id])
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def quiz_params
          params.require(:quiz).permit(:title)
        end
    end
  end
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/admin/quizzes/_form.html.erb
<%= form_for [:admin, @quiz], :html => {:class => "form-horizontal", :role => 'form'} do |f| %>
  <% if @quiz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quiz.errors.count, "error") %> prohibited this quiz from being saved:</h2>

      <ul>
      <% @quiz.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="space-4"></div>

  <%= render partial: 'form_fields', locals: { f: f } %>

  <div class="clearfix form-actions">
    <div class="col-md-offset-3 col-md-9">
      <button class="btn btn-info" type="submit"><i class="icon-ok bigger-110"></i> Submit</button>
    </div>
  </div>
<% end %>

app/views/admin/quizzes/_form_fields.html.erb
<div class="form-group">
  <%= f.label :id, "#{t('Id')}:", class: "control-label col-xs-12 col-sm-3 no-padding-right" %>
  <div class="col-xs-12 col-sm-9">
    <div class="clearfix">
      <%= f.text_field :id, disabled: true , class: "col-xs-12 col-sm-6"%>
    </div>
  </div>
</div>
<div class="space-2"></div>


<div class="form-group">
  <%= f.label :title, "#{t('Title')}:", class: "control-label col-xs-12 col-sm-3 no-padding-right" %>
  <div class="col-xs-12 col-sm-9">
    <div class="clearfix">
      <%= f.text_field :title, class: "col-xs-12 col-sm-6"%>
    </div>
  </div>
</div>
<div class="space-2"></div>



<div class="form-group">
  <%= f.label :quiz_informations, "#{t('Information')}s:", class: "control-label col-xs-12 col-sm-3 no-padding-right" %>
  <div class="clearfix">
    <div id="information" class="col-xs-12 col-sm-9">
      <%= f.fields_for :quiz_informations do |f_information| %>
          <%= render 'quiz_information_fields', f: f_information %>
      <% end %>
    </div>
  </div>
  <div class="col-xs-12 col-sm-9 col-sm-offset-3 select2-activator">
    <%= link_to_add_association 'Add Information', f, :quiz_informations,
                                'data-association-insertion-node' => "#information",
                                'data-association-insertion-method' => "append" %>
  </div>
</div>
<div class="space-2"></div>

app/views/admin/quizzes/_quiz_information_fields.html.erb
<div class="nested-fields">
  <%= f.hidden_field :id %>
  <%= f.select :information_id, Information.all.map { |c| ["#{truncate(c.challenge_text, length: 50, separator: ' ')} (#{c.id})", c.id] }, {}, {class: "col-xs-12 col-sm-3" }%>
  <%= link_to_remove_association 'Remove Information', f %>
  <div class="space-2"></div>
  <div class="clearfix"></div>
</div>

app/views/admin/quizzes/edit.html.erb
<h1>Editing quiz</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @quiz] %> |
<%= link_to 'Back', admin_quizzes_path %>

app/views/admin/quizzes/index.html.erb
<div class="row">
  <div class="col-md-6">
    <%= render :partial => 'shared/simple_search', :locals => { path: admin_quizzes_path} %>
  </div>


  <div class="col-md-offset-4 col-md-2 top-action">
    <%= link_to content_tag(:span, '', :class => %w(glyphicon glyphicon-plus)).html_safe + content_tag(:span, " #{t('New')} #{t('Quiz')}", :class => "action-label").html_safe, new_admin_quiz_path, :class => %w(btn btn-primary btn-block) %>
  </div>

  <div class="col-xs-12">
    <div class="table-responsive">
      <table id="sample-table-1" class="table table-striped table-bordered table-hover">
        <thead>
          <tr>
            <th>Id</th>
            <th>Title</th>
            <th>Created at</th>
            <th>Updated at</th>
            <th>Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @quizzes.each do |quiz| %>
            <tr>
                    <td><%= quiz.id %></td>
                    <td><%= quiz.title %></td>
                    <td><%= quiz.created_at %></td>
                    <td><%= quiz.updated_at %></td>
                    <td>
                <div class='visible-md visible-lg hidden-sm hidden-xs btn-group'>

                  <%= link_to edit_admin_quiz_path(quiz) do %>
                    <button class='btn btn-xs btn-info'><i class='icon-edit bigger-120'></i></button>
                  <% end %>
                  <%= link_to admin_quiz_path(quiz), method: :delete, data: { confirm: 'Are you sure?' } do %>
                    <button class='btn btn-xs btn-danger'><i class='icon-trash bigger-120'></i></button>
                  <% end %>
                </div>

                <div class='visible-xs visible-sm hidden-md hidden-lg'>
                  <div class="inline position-relative">
                    <button class="btn btn-minier btn-primary dropdown-toggle" data-toggle="dropdown"><i class="icon-cog icon-only bigger-110"></i></button>
                    <ul class="dropdown-menu dropdown-only-icon dropdown-yellow pull-right dropdown-caret dropdown-close">

                      <li>
                        <%= link_to edit_admin_quiz_path(quiz), :class => "tooltip-success" do %>
                          <span class="green"><i class="icon-edit bigger-120"></i></span>
                        <% end %>
                      </li>
                      <li>
                        <%= link_to admin_quiz_path(quiz), method: :delete, data: { confirm: 'Are you sure?' }, :class => "tooltip-error" do %>
                          <span class="red"><i class="icon-trash bigger-120"></i></span>
                        <% end %>
                      </li>
                    </ul>
                  </div>
                </div>
                
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div><!--/.table-responsive-->
  </div><!--/span-->
</div><!--/row-->

app/views/admin/quizzes/new.html.erb
<h1>New quiz</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_quizzes_path %>