config/routes.rb
Rails.application.routes.draw do

  get 'quiz/quiz'

  namespace :api do
    namespace :v1 do
      resources :quizzes
      resources :categories
      resources :information_types
      resources :answers
      resources :informations
      resources :quiz_informations
      resources :memes

      resources :answer_givens

      devise_scope :user do
        get '/password/edit' => 'fm_passwords#edit', as: 'edit_password'
        post '/password' => 'fm_passwords#create'
        put '/password' => 'fm_passwords#update'
        put '/users' => 'fm_registrations#update'
      end

      get '/jwt_token' => 'fm_jwt_token#show'
      post '/jwt_token' => 'fm_jwt_token#create'
      delete '/jwt_token' => 'fm_jwt_token#destroy'
      get 'api_authenticated_nothing' => 'fm_base#authenticated_nothing'
    end
  end

  namespace :admin do
    resources :quizzes
    resources :categories
    resources :information_types
    resources :answers
    resources :informations
    resources :quiz_informations
    resources :memes
    resources :users

    get 'admin_authenticated_nothing' => 'fm_base#admin_authenticated_nothing'
    get '/' => 'fm_base#admin_authenticated_nothing', as: 'root'
  end

  get 'quiz' => 'quiz#quiz'

  authenticate :user, lambda {|u| u.admin? || u.super_admin? } do
    apipie
  end

  devise_for :users

  unless Rails.env.test?
    get '*unmatched_route', :to => 'application#raise_not_found!'
  end

  root 'application#nothing'

end

app/models/meme.rb
class Meme < ApplicationRecord
  belongs_to :category

  mount_uploader :image_url, DefaultPictureUploader

  scope :for_user, -> (user) do
    all
  end
end

app/controllers/admin/memes_controller.rb
module Admin
  class MemesController < FmBaseController
    layout 'admin/admin'

    before_action :authenticate_admin!

    before_action :set_meme, only: [:show, :edit, :update, :destroy]

    # GET /memes
    # GET /memes.json
    def index
      @memes = Meme.all
      @memes = filter_simple_search(@memes, :id)
    end

    # GET /memes/1
    # GET /memes/1.json
    def show
    end

    # GET /memes/new
    def new
      @meme = Meme.new
    end

    # GET /memes/1/edit
    def edit
    end

    # POST /memes
    # POST /memes.json
    def create
      @meme = Meme.new(meme_params)

      respond_to do |format|
        if @meme.save
          format.html { redirect_to edit_admin_meme_path(@meme), notice: 'Meme was successfully created.' }
          format.json { render :show, status: :created, location: @meme }
        else
          format.html { render :new }
          format.json { render json: @meme.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /memes/1
    # PATCH/PUT /memes/1.json
    def update
      respond_to do |format|
        if @meme.update(meme_params)
          format.html { redirect_to edit_admin_meme_path(@meme), notice: 'Meme was successfully updated.' }
          format.json { render :show, status: :ok, location: @meme }
        else
          format.html { render :edit }
          format.json { render json: @meme.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /memes/1
    # DELETE /memes/1.json
    def destroy
      @meme.destroy
      respond_to do |format|
        format.html { redirect_to admin_memes_url }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_meme
        @meme = Meme.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def meme_params
        params.require(:meme).permit(:image_url, :category_id, :min_correct_including, :max_correct_excluding)
      end
  end
end

app/controllers/api/v1/memes_controller.rb
module Api
  module V1
    class MemesController < FmBaseController

      before_action :authenticate!
      before_action :set_meme, only: [:show, :update, :destroy]

      # GET /memes.json
      # DOC GENERATED AUTOMATICALLY: REMOVE THIS LINE TO PREVENT REGENARATING NEXT TIME
      api :GET, '/v1/memes', 'List memes'
      def index
        @memes = Meme.for_user(current_user)
      end

      # GET /memes/1.json
      # DOC GENERATED AUTOMATICALLY: REMOVE THIS LINE TO PREVENT REGENARATING NEXT TIME
      api :GET, '/v1/memes/:id', 'Show a meme'
      def show
      end

      # POST /memes.json
      def create
        @meme = Meme.new(meme_params)

        if @meme.save_with_user(current_user)
          render :show, status: :created, location: [:api, :v1, @meme]
        else
          render json: @meme.errors, status: :unprocessable_entity
        end
      end

      # PATCH/PUT /memes/1.json
      def update
        if @meme.update_with_user(current_user, meme_params)
          render :show, status: :ok, location: [:api, :v1, @meme]
        else
          render json: @meme.errors, status: :unprocessable_entity
        end
      end

      # DELETE /memes/1.json
      # DOC GENERATED AUTOMATICALLY: REMOVE THIS LINE TO PREVENT REGENARATING NEXT TIME
      api :DELETE, '/v1/memes/:id', 'Destroy a meme'
      def destroy
        @meme.destroy_with_user(current_user)
        head :no_content
      end

      private
        # Use callbacks to share common setup or constraints between actions.
        def set_meme
          @meme = Meme.for_user(current_user).find(params[:id])
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def meme_params
          params.require(:meme).permit(:image_url, :category_id, :min_correct_including, :max_correct_excluding)
        end
    end
  end
end

app/helpers/memes_helper.rb
module MemesHelper
end

app/views/admin/memes/_form.html.erb
<%= form_for [:admin, @meme], :html => {:class => "form-horizontal", :role => 'form'} do |f| %>
  <% if @meme.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meme.errors.count, "error") %> prohibited this meme from being saved:</h2>

      <ul>
      <% @meme.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="space-4"></div>

  <%= render partial: 'form_fields', locals: { f: f } %>

  <div class="clearfix form-actions">
    <div class="col-md-offset-3 col-md-9">
      <button class="btn btn-info" type="submit"><i class="icon-ok bigger-110"></i> Submit</button>
    </div>
  </div>
<% end %>

app/views/admin/memes/_form_fields.html.erb
<div class="form-group">
  <%= f.label :id, "#{t('Id')}:", class: "control-label col-xs-12 col-sm-3 no-padding-right" %>
  <div class="col-xs-12 col-sm-9">
    <div class="clearfix">
      <%= f.text_field :id, disabled: true , class: "col-xs-12 col-sm-6"%>
    </div>
  </div>
</div>
<div class="space-2"></div>


<div class="form-group">
  <%= f.label :image_url, "#{t('Image_url')}:", class: "control-label col-xs-12 col-sm-3 no-padding-right" %>
  <div class="col-xs-12 col-sm-9">
    <div class="clearfix">
      <%= f.file_field :image_url, class: "col-xs-12 col-sm-6"%>
    </div>
    <div class="space-8"></div>
    <% unless f.object.image_url.file.nil? || f.object.errors.count > 0 %>
        <div class="clearfix">
          <%= link_to '', data: { 'alert-id' => 'preview'} do %>
              Vorschau öffnen für <%= f.object.image_url.filename_without_hash %>
          <% end %>
        </div>
        <div class="clearfix">
          <%= link_to f.object.image_url.url, target: :_blank do %>
              Download <%= f.object.image_url.filename_without_hash %>
          <% end %>
        </div>
    <% end %>
  </div>
</div>
<div class="space-2"></div>


<div class="form-group">
  <%= f.label :category_id, "#{t('Category')}:", class: "control-label col-xs-12 col-sm-3 no-padding-right" %>
  <div class="col-xs-12 col-sm-9">
    <div class="clearfix">
      <%= f.select :category_id, Category.all.map { |category| [category.title, category.id] }, include_blank: true, class: "col-xs-12 col-sm-6"%>
    </div>
  </div>
</div>
<div class="space-2"></div>


<div class="form-group">
  <%= f.label :min_correct_including, "#{t('Min_correct_including')}:", class: "control-label col-xs-12 col-sm-3 no-padding-right" %>
  <div class="col-xs-12 col-sm-9">
    <div class="clearfix">
      <%= f.text_field :min_correct_including, class: "col-xs-12 col-sm-6"%>
    </div>
  </div>
</div>
<div class="space-2"></div>


<div class="form-group">
  <%= f.label :max_correct_excluding, "#{t('Max_correct_excluding')}:", class: "control-label col-xs-12 col-sm-3 no-padding-right" %>
  <div class="col-xs-12 col-sm-9">
    <div class="clearfix">
      <%= f.text_field :max_correct_excluding, class: "col-xs-12 col-sm-6"%>
    </div>
  </div>
</div>
<div class="space-2"></div>

app/views/admin/memes/edit.html.erb
<h1>Editing meme</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @meme] %> |
<%= link_to 'Back', admin_memes_path %>

app/views/admin/memes/index.html.erb
<div class="row">
  <div class="col-md-6">
    <%= render :partial => 'shared/simple_search', :locals => { path: admin_memes_path} %>
  </div>


  <div class="col-md-offset-4 col-md-2 top-action">
    <%= link_to content_tag(:span, '', :class => %w(glyphicon glyphicon-plus)).html_safe + content_tag(:span, " #{t('New')} #{t('Meme')}", :class => "action-label").html_safe, new_admin_meme_path, :class => %w(btn btn-primary btn-block) %>
  </div>

  <div class="col-xs-12">
    <div class="table-responsive">
      <table id="sample-table-1" class="table table-striped table-bordered table-hover">
        <thead>
          <tr>
            <th>Id</th>
            <th>Image url</th>
            <th>Category</th>
            <th>Min correct including</th>
            <th>Max correct excluding</th>
            <th>Created at</th>
            <th>Updated at</th>
            <th>Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @memes.each do |meme| %>
            <tr>
                    <td><%= meme.id %></td>
                    <td><%= meme.image_url %></td>
                    <td><%= "#{meme.category.title} (#{meme.category_id})" %></td>
                    <td><%= meme.min_correct_including %></td>
                    <td><%= meme.max_correct_excluding %></td>
                    <td><%= meme.created_at %></td>
                    <td><%= meme.updated_at %></td>
                    <td>
                <div class='visible-md visible-lg hidden-sm hidden-xs btn-group'>
                  <%= link_to edit_admin_meme_path(meme) do %>
                    <button class='btn btn-xs btn-info'><i class='icon-edit bigger-120'></i></button>
                  <% end %>
                  <%= link_to admin_meme_path(meme), method: :delete, data: { confirm: 'Are you sure?' } do %>
                    <button class='btn btn-xs btn-danger'><i class='icon-trash bigger-120'></i></button>
                  <% end %>
                </div>

                <div class='visible-xs visible-sm hidden-md hidden-lg'>
                  <div class="inline position-relative">
                    <button class="btn btn-minier btn-primary dropdown-toggle" data-toggle="dropdown"><i class="icon-cog icon-only bigger-110"></i></button>
                    <ul class="dropdown-menu dropdown-only-icon dropdown-yellow pull-right dropdown-caret dropdown-close">
                      <li>
                        <%= link_to edit_admin_meme_path(meme), :class => "tooltip-success" do %>
                          <span class="green"><i class="icon-edit bigger-120"></i></span>
                        <% end %>
                      </li>
                      <li>
                        <%= link_to admin_meme_path(meme), method: :delete, data: { confirm: 'Are you sure?' }, :class => "tooltip-error" do %>
                          <span class="red"><i class="icon-trash bigger-120"></i></span>
                        <% end %>
                      </li>
                    </ul>
                  </div>
                </div>
                
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div><!--/.table-responsive-->
  </div><!--/span-->
</div><!--/row-->

app/views/admin/memes/new.html.erb
<h1>New meme</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_memes_path %>