config/routes.rb
Rails.application.routes.draw do

  get 'quiz/quiz'

  namespace :api do
    namespace :v1 do
      resources :quizzes
      resources :categories
      resources :information_types
      resources :answers
      resources :informations
      resources :quiz_informations
      resources :memes

      resources :answer_givens

      devise_scope :user do
        get '/password/edit' => 'fm_passwords#edit', as: 'edit_password'
        post '/password' => 'fm_passwords#create'
        put '/password' => 'fm_passwords#update'
        put '/users' => 'fm_registrations#update'
      end

      get '/jwt_token' => 'fm_jwt_token#show'
      post '/jwt_token' => 'fm_jwt_token#create'
      delete '/jwt_token' => 'fm_jwt_token#destroy'
      get 'api_authenticated_nothing' => 'fm_base#authenticated_nothing'
    end
  end

  namespace :admin do
    resources :quizzes
    resources :categories
    resources :information_types
    resources :answers
    resources :informations
    resources :quiz_informations
    resources :memes
    resources :users

    get 'admin_authenticated_nothing' => 'fm_base#admin_authenticated_nothing'
    get '/' => 'fm_base#admin_authenticated_nothing', as: 'root'
  end

  get 'quiz' => 'quiz#quiz'

  authenticate :user, lambda {|u| u.admin? || u.super_admin? } do
    apipie
  end

  devise_for :users

  unless Rails.env.test?
    get '*unmatched_route', :to => 'application#raise_not_found!'
  end

  root 'application#nothing'

end

app/views/layouts/admin/_sidenav.html.erb
<a class="menu-toggler" id="menu-toggler" href="#"><span class="menu-text"></span></a>

<div class="sidebar sidebar-fixed" id="sidebar">
	<script type="text/javascript">
	try{ace.settings.check('sidebar' , 'fixed')}catch(e){}
	</script>
	
	<ul class="nav nav-list">

<!-- 		{{#layout.sidenav_navList}}
			{{> layout.sidenav.items}}
		{{/layout.sidenav_navList}} -->
    <li>
      <%= link_to admin_quizzes_path do %>
          <i class="icon-user"></i>
          <span class="menu-text"> <%= title_by_path(admin_quizzes_path) %> </span>
      <% end %>
    </li>

    <li>
      <%= link_to admin_categories_path do %>
          <i class="icon-user"></i>
          <span class="menu-text"> <%= title_by_path(admin_categories_path) %> </span>
      <% end %>
    </li>
    <li>
      <%= link_to admin_information_types_path do %>
          <i class="icon-user"></i>
          <span class="menu-text"> <%= title_by_path(admin_information_types_path) %> </span>
      <% end %>
    </li>
    <li>
      <%= link_to admin_answers_path do %>
          <i class="icon-user"></i>
          <span class="menu-text"> <%= title_by_path(admin_answers_path) %> </span>
      <% end %>
    </li>
    <li>
      <%= link_to admin_informations_path do %>
          <i class="icon-user"></i>
          <span class="menu-text"> <%= title_by_path(admin_informations_path) %> </span>
      <% end %>
    </li>
<!--    <li>
      <%= link_to admin_quiz_informations_path do %>
          <i class="icon-user"></i>
          <span class="menu-text"> <%= title_by_path(admin_quiz_informations_path) %> </span>
      <% end %>
    </li>-->
    <li>
      <%= link_to admin_memes_path do %>
          <i class="icon-user"></i>
          <span class="menu-text"> <%= title_by_path(admin_memes_path) %> </span>
      <% end %>
    </li>

    <li>
      <%= link_to admin_users_path do %>
          <i class="icon-user"></i>
          <span class="menu-text"> <%= title_by_path(admin_users_path) %> </span>
      <% end %>
    </li>


    <% if current_user.super_admin? %>
    <% end %>





      <% if false %>
      <!--<li>-->
        <!--<%= link_to admin_posts_path do %>-->
          <!--<i class="icon-file"></i>-->
          <!--<span class="menu-text"> <%= title_by_path(admin_posts_path) %> </span>-->
        <!--<% end %>-->
      <!--</li>-->


      <!--<li>-->
        <!--<%= link_to admin_programs_path do %>-->
            <!--<i class="icon-calendar"></i>-->
            <!--<span class="menu-text"> <%= title_by_path(admin_programs_path) %> </span>-->
        <!--<% end %>-->
      <!--</li>-->

      <!--<li>-->
        <!--<%= link_to admin_locations_path do %>-->
          <!--<i class="icon-pushpin"></i>-->
          <!--<span class="menu-text"> <%= title_by_path(admin_locations_path) %> </span>-->
        <!--<% end %>-->
      <!--</li>-->
  <!---->
      <!--<li>-->
        <!--<%= link_to admin_public_transports_path do %>-->
          <!--<i class="glyphicon glyphicon-transfer"></i>-->
          <!--<span class="menu-text"> <%= title_by_path(admin_public_transports_path) %> </span>-->
        <!--<% end %>-->
      <!--</li>-->

      <!--<li>-->
          <!--<%= link_to new_admin_notification_path do %>-->
              <!--<i class="icon-envelope"></i>-->
              <!--<span class="menu-text"> <%= t('Notifications') %> </span>-->
          <!--<% end %>-->
      <!--</li>-->

      <!--<li>-->
        <!--<%= link_to admin_users_path do %>-->
          <!--<i class="icon-group"></i>-->
          <!--<span class="menu-text"> <%= title_by_path(admin_users_path) %> </span>-->
        <!--<% end %>-->
      <!--</li>-->
  <!---->
      <!--<li>-->
        <!--<%= link_to admin_dashboard_path do %>-->
          <!--<i class="icon-dashboard"></i>-->
          <!--<span class="menu-text"> <%= title_by_path(admin_dashboard_path) %> </span>-->
        <!--<% end %>-->
      <!--</li>-->
  <!---->
      <!--<li>-->
        <!--<%= link_to admin_orders_path do %>-->
          <!--<i class="icon-truck"></i>-->
          <!--<span class="menu-text"> <%= title_by_path(admin_orders_path) %> </span>-->
        <!--<% end %>-->
      <!--</li>-->
  <!---->
      <!--<li>-->
        <!--<%= link_to admin_categories_path do %>-->
          <!--<i class="icon-bookmark"></i>-->
          <!--<span class="menu-text"> <%= title_by_path(admin_categories_path) %> </span>-->
        <!--<% end %>-->
      <!--</li>-->
  <!---->
      <!--<li>-->
        <!--<%= link_to admin_products_path do %>-->
          <!--<i class="icon-barcode"></i>-->
          <!--<span class="menu-text"> <%= title_by_path(admin_products_path) %> </span>-->
        <!--<%end %>-->
      <!--</li>-->
  <!---->
      <!--&lt;!&ndash; <li>-->
        <!--<%= link_to admin_preferences_path do %>-->
          <!--<i class="icon-cogs"></i>-->
          <!--<span class="menu-text"> <%= title_by_path(admin_preferences_path) %> </span>-->
        <!--<% end %>-->
      <!--</li> &ndash;&gt;-->
  <!---->
      <!--<li>-->
        <!--<%= link_to admin_import_path do %>-->
          <!--<i class="icon-download"></i>-->
          <!--<span class="menu-text"> <%= title_by_path(admin_import_path) %> </span>-->
        <!--<% end %>-->
        <!--</li>-->
		<% end %><!--<#% if false %>-->

	</ul><!--/.nav-list-->


	<script type="text/javascript">
	try{ace.settings.check('sidebar' , 'collapsed')}catch(e){}
	</script>
</div>

app/views/layouts/admin/admin.html.erb
<!DOCTYPE html>
<html lang="de">
	
	<%= render :partial => 'layouts/header' %>
	
	<!-- {{> layout._template.header}} -->

	<body class="skin-1 navbar-fixed">
    <div id="overlay">
      <span class="spinner"></span>
    </div>
	<%= render :partial => 'layouts/topbar' %>
	<!-- {{> layout.topbar}} -->

		<div class="main-container" id="main-container">
		 <div class="main-container-inner">

		 	<%= render :partial => 'layouts/admin/sidenav' %>
		 <!-- {{> layout.sidenav}} -->

			<div class="main-content">
				<%#= render :partial => 'layouts/breadcrumbs' %>
				<!-- {{> layout.breadcrumbs}} -->

				<div class="page-content">
					<!-- {{^page.no-header}}{{!if no such thing as "no-header", then print header}} -->
					<div class="page-header">
						<h1><%= title_by_path(request.path) %> <small><i class="icon-double-angle-right"></i> <%= description_by_path(request.path) %></small></h1>
					</div><!--/.page-header-->
					<!-- {{/page.no-header}} -->

					<div class="row">
                        <%= render partial: "shared/flash" %>
						<div class="col-xs-12">
							<%= yield %>
						</div><!--/.col-->
					</div><!--/.row-->

				</div><!--/.page-content-->

			</div><!--/.main-content -->

			<!-- {{> layout.settings}} -->
		 </div><!--/.main-container-inner-->

		 <a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
			<i class="icon-double-angle-up icon-only bigger-110"></i>
		 </a>
		</div><!--/.main-container-->

		<!-- {{> layout._template.footer}} -->

	</body>
</html>